pipeline {
    agent {
        node {
            label 'platform'
        }
    }

    environment {
        WORKSPACE      = 'alper'
        PROJECT        = 'mobile'
        CONFIG_DIR     = 'sadf'
        NAMESPACE      = 'alper-prod'
        CUSTOMER_CODE_DIR = "/home/generated-apps/temp/platform/alper/mobile"
    }

    stages {
        stage('Prepare Temporary Workspace') {
            steps {
                script {
                    echo 'Preparing temporary workspace for build...'
                    sh '''
                        mkdir -p frontend-temp backend-temp
                        cp -R ${CUSTOMER_CODE_DIR}/${CONFIG_DIR}/Backend/* backend-temp/
                    '''
                }
            }
        }

        stage('Build Backend Image') {
            steps {
                script {
                    def projectLower   = env.PROJECT.toLowerCase()
                    def workspaceLower = env.WORKSPACE.toLowerCase()
                    def namespaceLower = env.NAMESPACE.toLowerCase()

                    dir('backend-temp') {
                        echo 'Building Docker image for Backend...'
                        sh "docker buildx build --platform linux/amd64 -t kuika/${projectLower}-${workspaceLower}-${namespaceLower}.kuika.com-backend:${env.BUILD_NUMBER} --load ."
                    }
                }
            }
        }

        stage('Push Images to GCP Artifact Registry') {
            steps {
                script {
                    def projectLower   = env.PROJECT.toLowerCase()
                    def workspaceLower = env.WORKSPACE.toLowerCase()
                    def namespaceLower = env.NAMESPACE.toLowerCase()

                    def images = [
                        "kuika/${projectLower}-${workspaceLower}-${namespaceLower}.kuika.com-backend:${env.BUILD_NUMBER}"
                    ]

                    images.each { image ->
                        sh """
                            gcloud auth configure-docker europe-west4-docker.pkg.dev
                            docker tag ${image} europe-west4-docker.pkg.dev/kuikacloudservers/docker-repository/${image}
                            docker push europe-west4-docker.pkg.dev/kuikacloudservers/docker-repository/${image}
                        """
                    }
                }
            }
        }
    }

    post {
        always {
            echo "Cleaning workspace..."
            cleanWs()
        }
    }
}
